version: "3.7"

services:
  customer-registration:
    image: axonquiz/customer-registration:latest
    environment:
      SPRING_PROFILES_ACTIVE: swarm
    networks:
      - axon-quiz

networks:
  axon-quiz:
    external: true
