version: "3.7"

services:
  account-registration:
    image: axonquiz/account-registration:latest
    environment:
      SPRING_PROFILES_ACTIVE: swarm
    networks:
      - axon-quiz

networks:
  axon-quiz:
    external: true
