version: "3.7"

services:
  cards-command:
    image: axonquiz/cards-command:latest
    environment:
      SPRING_PROFILES_ACTIVE: swarm
    networks:
      - axon-quiz

networks:
  axon-quiz:
    external: true
