version: "3.7"

services:
  accounts-command:
    image: axonquiz/accounts-command:latest
    environment:
      SPRING_PROFILES_ACTIVE: swarm
    networks:
      - axon-quiz

networks:
  axon-quiz:
    external: true
