version: "3.7"

services:
  interfaces-http:
    image: axonquiz/interfaces-http:latest
    environment:
      SPRING_PROFILES_ACTIVE: swarm
    networks:
      - axon-quiz

networks:
  axon-quiz:
    external: true
